name: tests

on:
  push:
    paths:
      - '**/*.rs'
      - '.github/workflows/tests.yml'
      - 'Cargo.toml'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.rs'
      - '.github/workflows/tests.yml'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always
  SPACEAGE_VERSION_POSTFIX: "-test"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install dependencies"
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev
          rustup update
          rustc --version
      - name: "Build"
        run: cargo build --verbose
      - name: "Check codestyle"
        run: cargo fmt -- --check --verbose
      - name: "Check clippy warnings"
        run: cargo clippy -- -Dwarnings --verbose
      - name: "Run tests"
        run: cargo test --verbose
